# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Customizing Blacklight
tagline:             'Tutorial Series'
description:         'Click the links below to see high-level pages about customizing parts of your Blacklight application.'
url:                 http://lanyon.getpoole.com
baseurl:             '/'
paginate:            5
gems:                ["jekyll-paginate"]
highlighter:         rouge
plugins:
  - jekyll-redirect-from

# Custom vars
blacklight_versions:
  - v5.14.0
  - v7.0.0
